-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.32-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.10.0.7000
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando estructura para tabla constructora.clientes
CREATE TABLE IF NOT EXISTS `clientes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pais_id` int(11) unsigned DEFAULT NULL,
  `cif` varchar(15) DEFAULT NULL,
  `nombre` varchar(100) DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `correo` varchar(255) DEFAULT NULL,
  `cuenta_corriente` varchar(255) DEFAULT NULL,
  `moneda` varchar(255) DEFAULT NULL,
  `importe_mensual` decimal(20,6) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pais_id` (`pais_id`),
  CONSTRAINT `FK_clientes_paises` FOREIGN KEY (`pais_id`) REFERENCES `paises` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla constructora.clientes: ~0 rows (aproximadamente)
DELETE FROM `clientes`;

-- Volcando estructura para tabla constructora.cuota
CREATE TABLE IF NOT EXISTS `cuota` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` int(11) DEFAULT NULL,
  `remesa_id` int(11) DEFAULT NULL,
  `concepto` varchar(255) DEFAULT NULL,
  `fecha_emision` timestamp NULL DEFAULT NULL,
  `importe` decimal(20,6) DEFAULT NULL,
  `pagada` tinyint(4) DEFAULT NULL,
  `fecha_pago` tinyint(4) DEFAULT NULL,
  `notas` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cliente_id` (`cliente_id`),
  KEY `remesa_id` (`remesa_id`),
  CONSTRAINT `FK_cuota_clientes` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_cuota_remesa` FOREIGN KEY (`remesa_id`) REFERENCES `remesa` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla constructora.cuota: ~0 rows (aproximadamente)
DELETE FROM `cuota`;

-- Volcando estructura para tabla constructora.paises
CREATE TABLE IF NOT EXISTS `paises` (
  `id` int(11) unsigned NOT NULL,
  `iso2` char(2) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `iso3` char(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `prefijo` smallint(5) unsigned NOT NULL,
  `nombre` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `continente` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `subcontinente` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `iso_moneda` varchar(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `nombre_moneda` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `iso2` (`iso2`),
  UNIQUE KEY `iso3` (`iso3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla constructora.paises: ~241 rows (aproximadamente)
DELETE FROM `paises`;
INSERT INTO `paises` (`id`, `iso2`, `iso3`, `prefijo`, `nombre`, `continente`, `subcontinente`, `iso_moneda`, `nombre_moneda`) VALUES
	(4, 'AF', 'AFG', 93, 'Afganist�n', 'Asia', NULL, 'AFN', 'Afgani afgano'),
	(8, 'AL', 'ALB', 355, 'Albania', 'Europa', NULL, 'ALL', 'Lek alban�s'),
	(10, 'AQ', 'ATA', 672, 'Ant�rtida', 'Ant�rtida', NULL, NULL, NULL),
	(12, 'DZ', 'DZA', 213, 'Argelia', '�frica', NULL, 'DZD', 'Dinar algerino'),
	(16, 'AS', 'ASM', 1684, 'Samoa Americana', 'Ocean�a', NULL, NULL, NULL),
	(20, 'AD', 'AND', 376, 'Andorra', 'Europa', NULL, 'EUR', 'Euro'),
	(24, 'AO', 'AGO', 244, 'Angola', '�frica', NULL, 'AOA', 'Kwanza angole�o'),
	(28, 'AG', 'ATG', 1268, 'Antigua y Barbuda', 'Am�rica', 'El Caribe', NULL, NULL),
	(31, 'AZ', 'AZE', 994, 'Azerbaiy�n', 'Asia', NULL, 'AZM', 'Manat azerbaiyano'),
	(32, 'AR', 'ARG', 54, 'Argentina', 'Am�rica', 'Am�rica del Sur', 'ARS', 'Peso argentino'),
	(36, 'AU', 'AUS', 61, 'Australia', 'Ocean�a', NULL, 'AUD', 'D�lar australiano'),
	(40, 'AT', 'AUT', 43, 'Austria', 'Europa', NULL, 'EUR', 'Euro'),
	(44, 'BS', 'BHS', 1242, 'Bahamas', 'Am�rica', 'El Caribe', 'BSD', 'D�lar bahame�o'),
	(48, 'BH', 'BHR', 973, 'Bahr�in', 'Asia', NULL, 'BHD', 'Dinar bahrein�'),
	(50, 'BD', 'BGD', 880, 'Bangladesh', 'Asia', NULL, 'BDT', 'Taka de Bangladesh'),
	(51, 'AM', 'ARM', 374, 'Armenia', 'Asia', NULL, 'AMD', 'Dram armenio'),
	(52, 'BB', 'BRB', 1246, 'Barbados', 'Am�rica', 'El Caribe', 'BBD', 'D�lar de Barbados'),
	(56, 'BE', 'BEL', 32, 'B�lgica', 'Europa', NULL, 'EUR', 'Euro'),
	(60, 'BM', 'BMU', 1441, 'Bermudas', 'Am�rica', 'El Caribe', 'BMD', 'D�lar de Bermuda'),
	(64, 'BT', 'BTN', 975, 'Bhut�n', 'Asia', NULL, 'BTN', 'Ngultrum de But�n'),
	(68, 'BO', 'BOL', 591, 'Bolivia', 'Am�rica', 'Am�rica del Sur', 'BOB', 'Boliviano'),
	(70, 'BA', 'BIH', 387, 'Bosnia y Herzegovina', 'Europa', NULL, 'BAM', 'Marco convertible de Bosnia-Herzegovina'),
	(72, 'BW', 'BWA', 267, 'Botsuana', '�frica', NULL, 'BWP', 'Pula de Botsuana'),
	(74, 'BV', 'BVT', 0, 'Isla Bouvet', NULL, NULL, NULL, NULL),
	(76, 'BR', 'BRA', 55, 'Brasil', 'Am�rica', 'Am�rica del Sur', 'BRL', 'Real brasile�o'),
	(84, 'BZ', 'BLZ', 501, 'Belice', 'Am�rica', 'Am�rica Central', 'BZD', 'D�lar de Belice'),
	(86, 'IO', 'IOT', 0, 'Territorio Brit�nico del Oc�ano �ndico', NULL, NULL, NULL, NULL),
	(90, 'SB', 'SLB', 677, 'Islas Salom�n', 'Ocean�a', NULL, 'SBD', 'D�lar de las Islas Salom�n'),
	(92, 'VG', 'VGB', 1284, 'Islas V�rgenes Brit�nicas', 'Am�rica', 'El Caribe', NULL, NULL),
	(96, 'BN', 'BRN', 673, 'Brun�i', 'Asia', NULL, 'BND', 'D�lar de Brun�i'),
	(100, 'BG', 'BGR', 359, 'Bulgaria', 'Europa', NULL, 'BGN', 'Lev b�lgaro'),
	(104, 'MM', 'MMR', 95, 'Myanmar', 'Asia', NULL, 'MMK', 'Kyat birmano'),
	(108, 'BI', 'BDI', 257, 'Burundi', '�frica', NULL, 'BIF', 'Franco burund�s'),
	(112, 'BY', 'BLR', 375, 'Bielorrusia', 'Europa', NULL, 'BYR', 'Rublo bielorruso'),
	(116, 'KH', 'KHM', 855, 'Camboya', 'Asia', NULL, 'KHR', 'Riel camboyano'),
	(120, 'CM', 'CMR', 237, 'Camer�n', '�frica', NULL, NULL, NULL),
	(124, 'CA', 'CAN', 1, 'Canad�', 'Am�rica', 'Am�rica del Norte', 'CAD', 'D�lar canadiense'),
	(132, 'CV', 'CPV', 238, 'Cabo Verde', '�frica', NULL, 'CVE', 'Escudo caboverdiano'),
	(136, 'KY', 'CYM', 1345, 'Islas Caim�n', 'Am�rica', 'El Caribe', 'KYD', 'D�lar caimano (de Islas Caim�n)'),
	(140, 'CF', 'CAF', 236, 'Rep�blica Centroafricana', '�frica', NULL, NULL, NULL),
	(144, 'LK', 'LKA', 94, 'Sri Lanka', 'Asia', NULL, 'LKR', 'Rupia de Sri Lanka'),
	(148, 'TD', 'TCD', 235, 'Chad', '�frica', NULL, NULL, NULL),
	(152, 'CL', 'CHL', 56, 'Chile', 'Am�rica', 'Am�rica del Sur', 'CLP', 'Peso chileno'),
	(156, 'CN', 'CHN', 86, 'China', 'Asia', NULL, 'CNY', 'Yuan Renminbi de China'),
	(158, 'TW', 'TWN', 886, 'Taiw�n', 'Asia', NULL, 'TWD', 'D�lar taiwan�s'),
	(162, 'CX', 'CXR', 61, 'Isla de Navidad', 'Ocean�a', NULL, NULL, NULL),
	(166, 'CC', 'CCK', 61, 'Islas Cocos', '�cean�a', NULL, NULL, NULL),
	(170, 'CO', 'COL', 57, 'Colombia', 'Am�rica', 'Am�rica del Sur', 'COP', 'Peso colombiano'),
	(174, 'KM', 'COM', 269, 'Comoras', '�frica', NULL, 'KMF', 'Franco comoriano (de Comoras)'),
	(175, 'YT', 'MYT', 262, 'Mayotte', '�frica', NULL, NULL, NULL),
	(178, 'CG', 'COG', 242, 'Congo', '�frica', NULL, NULL, NULL),
	(180, 'CD', 'COD', 243, 'Rep�blica Democr�tica del Congo', '�frica', NULL, 'CDF', 'Franco congole�o'),
	(184, 'CK', 'COK', 682, 'Islas Cook', 'Ocean�a', NULL, NULL, NULL),
	(188, 'CR', 'CRI', 506, 'Costa Rica', 'Am�rica', 'Am�rica Central', 'CRC', 'Col�n costarricense'),
	(191, 'HR', 'HRV', 385, 'Croacia', 'Europa', NULL, 'HRK', 'Kuna croata'),
	(192, 'CU', 'CUB', 53, 'Cuba', 'Am�rica', 'El Caribe', 'CUP', 'Peso cubano'),
	(196, 'CY', 'CYP', 357, 'Chipre', 'Europa', NULL, 'CYP', 'Libra chipriota'),
	(203, 'CZ', 'CZE', 420, 'Rep�blica Checa', 'Europa', NULL, 'CZK', 'Koruna checa'),
	(204, 'BJ', 'BEN', 229, 'Ben�n', '�frica', NULL, NULL, NULL),
	(208, 'DK', 'DNK', 45, 'Dinamarca', 'Europa', NULL, 'DKK', 'Corona danesa'),
	(212, 'DM', 'DMA', 1767, 'Dominica', 'Am�rica', 'El Caribe', NULL, NULL),
	(214, 'DO', 'DOM', 1809, 'Rep�blica Dominicana', 'Am�rica', 'El Caribe', 'DOP', 'Peso dominicano'),
	(218, 'EC', 'ECU', 593, 'Ecuador', 'Am�rica', 'Am�rica del Sur', NULL, NULL),
	(222, 'SV', 'SLV', 503, 'El Salvador', 'Am�rica', 'Am�rica Central', 'SVC', 'Col�n salvadore�o'),
	(226, 'GQ', 'GNQ', 240, 'Guinea Ecuatorial', '�frica', NULL, NULL, NULL),
	(231, 'ET', 'ETH', 251, 'Etiop�a', '�frica', NULL, 'ETB', 'Birr et�ope'),
	(232, 'ER', 'ERI', 291, 'Eritrea', '�frica', NULL, 'ERN', 'Nakfa eritreo'),
	(233, 'EE', 'EST', 372, 'Estonia', 'Europa', NULL, 'EEK', 'Corona estonia'),
	(234, 'FO', 'FRO', 298, 'Islas Feroe', 'Europa', NULL, NULL, NULL),
	(238, 'FK', 'FLK', 500, 'Islas Malvinas', 'Am�rica', 'Am�rica del Sur', 'FKP', 'Libra malvinense'),
	(239, 'GS', 'SGS', 0, 'Islas Georgias del Sur y Sandwich del Sur', 'Am�rica', 'Am�rica del Sur', NULL, NULL),
	(242, 'FJ', 'FJI', 679, 'Fiyi', 'Ocean�a', NULL, 'FJD', 'D�lar fijiano'),
	(246, 'FI', 'FIN', 358, 'Finlandia', 'Europa', NULL, 'EUR', 'Euro'),
	(248, 'AX', 'ALA', 0, 'Islas Gland', 'Europa', NULL, NULL, NULL),
	(250, 'FR', 'FRA', 33, 'Francia', 'Europa', NULL, 'EUR', 'Euro'),
	(254, 'GF', 'GUF', 0, 'Guayana Francesa', 'Am�rica', 'Am�rica del Sur', NULL, NULL),
	(258, 'PF', 'PYF', 689, 'Polinesia Francesa', 'Ocean�a', NULL, NULL, NULL),
	(260, 'TF', 'ATF', 0, 'Territorios Australes Franceses', NULL, NULL, NULL, NULL),
	(262, 'DJ', 'DJI', 253, 'Yibuti', '�frica', NULL, 'DJF', 'Franco yibutiano'),
	(266, 'GA', 'GAB', 241, 'Gab�n', '�frica', NULL, NULL, NULL),
	(268, 'GE', 'GEO', 995, 'Georgia', 'Europa', NULL, 'GEL', 'Lari georgiano'),
	(270, 'GM', 'GMB', 220, 'Gambia', '�frica', NULL, 'GMD', 'Dalasi gambiano'),
	(275, 'PS', 'PSE', 0, 'Palestina', 'Asia', NULL, NULL, NULL),
	(276, 'DE', 'DEU', 49, 'Alemania', 'Europa', NULL, 'EUR', 'Euro'),
	(288, 'GH', 'GHA', 233, 'Ghana', '�frica', NULL, 'GHC', 'Cedi ghan�s'),
	(292, 'GI', 'GIB', 350, 'Gibraltar', 'Europa', NULL, 'GIP', 'Libra de Gibraltar'),
	(296, 'KI', 'KIR', 686, 'Kiribati', 'Ocean�a', NULL, NULL, NULL),
	(300, 'GR', 'GRC', 30, 'Grecia', 'Europa', NULL, 'EUR', 'Euro'),
	(304, 'GL', 'GRL', 299, 'Groenlandia', 'Am�rica', 'Am�rica del Norte', NULL, NULL),
	(308, 'GD', 'GRD', 1473, 'Granada', 'Am�rica', 'El Caribe', NULL, NULL),
	(312, 'GP', 'GLP', 0, 'Guadalupe', 'Am�rica', 'El Caribe', NULL, NULL),
	(316, 'GU', 'GUM', 1671, 'Guam', 'Ocean�a', NULL, NULL, NULL),
	(320, 'GT', 'GTM', 502, 'Guatemala', 'Am�rica', 'Am�rica Central', 'GTQ', 'Quetzal guatemalteco'),
	(324, 'GN', 'GIN', 224, 'Guinea', '�frica', NULL, 'GNF', 'Franco guineano'),
	(328, 'GY', 'GUY', 592, 'Guyana', 'Am�rica', 'Am�rica del Sur', 'GYD', 'D�lar guyan�s'),
	(332, 'HT', 'HTI', 509, 'Hait�', 'Am�rica', 'El Caribe', 'HTG', 'Gourde haitiano'),
	(334, 'HM', 'HMD', 0, 'Islas Heard y McDonald', 'Ocean�a', NULL, NULL, NULL),
	(336, 'VA', 'VAT', 39, 'Ciudad del Vaticano', 'Europa', NULL, NULL, NULL),
	(340, 'HN', 'HND', 504, 'Honduras', 'Am�rica', 'Am�rica Central', 'HNL', 'Lempira hondure�o'),
	(344, 'HK', 'HKG', 852, 'Hong Kong', 'Asia', NULL, 'HKD', 'D�lar de Hong Kong'),
	(348, 'HU', 'HUN', 36, 'Hungr�a', 'Europa', NULL, 'HUF', 'Forint h�ngaro'),
	(352, 'IS', 'ISL', 354, 'Islandia', 'Europa', NULL, 'ISK', 'Kr�na islandesa'),
	(356, 'IN', 'IND', 91, 'India', 'Asia', NULL, 'INR', 'Rupia india'),
	(360, 'ID', 'IDN', 62, 'Indonesia', 'Asia', NULL, 'IDR', 'Rupiah indonesia'),
	(364, 'IR', 'IRN', 98, 'Ir�n', 'Asia', NULL, 'IRR', 'Rial iran�'),
	(368, 'IQ', 'IRQ', 964, 'Iraq', 'Asia', NULL, 'IQD', 'Dinar iraqu�'),
	(372, 'IE', 'IRL', 353, 'Irlanda', 'Europa', NULL, 'EUR', 'Euro'),
	(376, 'IL', 'ISR', 972, 'Israel', 'Asia', NULL, 'ILS', 'Nuevo sh�quel israel�'),
	(380, 'IT', 'ITA', 39, 'Italia', 'Europa', NULL, 'EUR', 'Euro'),
	(384, 'CI', 'CIV', 225, 'Costa de Marfil', '�frica', NULL, NULL, NULL),
	(388, 'JM', 'JAM', 1876, 'Jamaica', 'Am�rica', 'El Caribe', 'JMD', 'D�lar jamaicano'),
	(392, 'JP', 'JPN', 81, 'Jap�n', 'Asia', NULL, 'JPY', 'Yen japon�s'),
	(398, 'KZ', 'KAZ', 7, 'Kazajst�n', 'Asia', NULL, 'KZT', 'Tenge kazajo'),
	(400, 'JO', 'JOR', 962, 'Jordania', 'Asia', NULL, 'JOD', 'Dinar jordano'),
	(404, 'KE', 'KEN', 254, 'Kenia', '�frica', NULL, 'KES', 'Chel�n keniata'),
	(408, 'KP', 'PRK', 850, 'Corea del Norte', 'Asia', NULL, 'KPW', 'Won norcoreano'),
	(410, 'KR', 'KOR', 82, 'Corea del Sur', 'Asia', NULL, 'KRW', 'Won surcoreano'),
	(414, 'KW', 'KWT', 965, 'Kuwait', 'Asia', NULL, 'KWD', 'Dinar kuwait�'),
	(417, 'KG', 'KGZ', 996, 'Kirguist�n', 'Asia', NULL, 'KGS', 'Som kirgu�s (de Kirguist�n)'),
	(418, 'LA', 'LAO', 856, 'Laos', 'Asia', NULL, 'LAK', 'Kip lao'),
	(422, 'LB', 'LBN', 961, 'L�bano', 'Asia', NULL, 'LBP', 'Libra libanesa'),
	(426, 'LS', 'LSO', 266, 'Lesotho', '�frica', NULL, 'LSL', 'Loti lesotense'),
	(428, 'LV', 'LVA', 371, 'Letonia', 'Europa', NULL, 'LVL', 'Lat let�n'),
	(430, 'LR', 'LBR', 231, 'Liberia', '�frica', NULL, 'LRD', 'D�lar liberiano'),
	(434, 'LY', 'LBY', 218, 'Libia', '�frica', NULL, 'LYD', 'Dinar libio'),
	(438, 'LI', 'LIE', 423, 'Liechtenstein', 'Europa', NULL, NULL, NULL),
	(440, 'LT', 'LTU', 370, 'Lituania', 'Europa', NULL, 'LTL', 'Litas lituano'),
	(442, 'LU', 'LUX', 352, 'Luxemburgo', 'Europa', NULL, 'EUR', 'Euro'),
	(446, 'MO', 'MAC', 853, 'Macao', 'Asia', NULL, 'MOP', 'Pataca de Macao'),
	(450, 'MG', 'MDG', 261, 'Madagascar', '�frica', NULL, 'MGA', 'Ariary malgache'),
	(454, 'MW', 'MWI', 265, 'Malaui', '�frica', NULL, 'MWK', 'Kwacha malauiano'),
	(458, 'MY', 'MYS', 60, 'Malasia', 'Asia', NULL, 'MYR', 'Ringgit malayo'),
	(462, 'MV', 'MDV', 960, 'Maldivas', 'Asia', NULL, 'MVR', 'Rufiyaa maldiva'),
	(466, 'ML', 'MLI', 223, 'Mal�', '�frica', NULL, NULL, NULL),
	(470, 'MT', 'MLT', 356, 'Malta', 'Europa', NULL, 'MTL', 'Lira maltesa'),
	(474, 'MQ', 'MTQ', 0, 'Martinica', 'Am�rica', 'El Caribe', NULL, NULL),
	(478, 'MR', 'MRT', 222, 'Mauritania', '�frica', NULL, 'MRO', 'Ouguiya mauritana'),
	(480, 'MU', 'MUS', 230, 'Mauricio', '�frica', NULL, 'MUR', 'Rupia mauricia'),
	(484, 'MX', 'MEX', 52, 'M�xico', 'Am�rica', 'Am�rica del Norte', 'MXN', 'Peso mexicano'),
	(492, 'MC', 'MCO', 377, 'M�naco', 'Europa', NULL, NULL, NULL),
	(496, 'MN', 'MNG', 976, 'Mongolia', 'Asia', NULL, 'MNT', 'Tughrik mongol'),
	(498, 'MD', 'MDA', 373, 'Moldavia', 'Europa', NULL, 'MDL', 'Leu moldavo'),
	(499, 'ME', 'MNE', 382, 'Montenegro', 'Europa', NULL, NULL, NULL),
	(500, 'MS', 'MSR', 1664, 'Montserrat', 'Am�rica', 'El Caribe', NULL, NULL),
	(504, 'MA', 'MAR', 212, 'Marruecos', '�frica', NULL, 'MAD', 'Dirham marroqu�'),
	(508, 'MZ', 'MOZ', 258, 'Mozambique', '�frica', NULL, 'MZM', 'Metical mozambique�o'),
	(512, 'OM', 'OMN', 968, 'Om�n', 'Asia', NULL, 'OMR', 'Rial oman�'),
	(516, 'NA', 'NAM', 264, 'Namibia', '�frica', NULL, 'NAD', 'D�lar namibio'),
	(520, 'NR', 'NRU', 674, 'Nauru', 'Ocean�a', NULL, NULL, NULL),
	(524, 'NP', 'NPL', 977, 'Nepal', 'Asia', NULL, 'NPR', 'Rupia nepalesa'),
	(528, 'NL', 'NLD', 31, 'Pa�ses Bajos', 'Europa', NULL, 'EUR', 'Euro'),
	(530, 'AN', 'ANT', 599, 'Antillas Holandesas', 'Am�rica', 'El Caribe', 'ANG', 'Flor�n antillano neerland�s'),
	(533, 'AW', 'ABW', 297, 'Aruba', 'Am�rica', 'El Caribe', 'AWG', 'Flor�n arube�o'),
	(540, 'NC', 'NCL', 687, 'Nueva Caledonia', 'Ocean�a', NULL, NULL, NULL),
	(548, 'VU', 'VUT', 678, 'Vanuatu', 'Ocean�a', NULL, 'VUV', 'Vatu vanuatense'),
	(554, 'NZ', 'NZL', 64, 'Nueva Zelanda', 'Ocean�a', NULL, 'NZD', 'D�lar neozeland�s'),
	(558, 'NI', 'NIC', 505, 'Nicaragua', 'Am�rica', 'Am�rica Central', 'NIO', 'C�rdoba nicarag�ense'),
	(562, 'NE', 'NER', 227, 'N�ger', '�frica', NULL, NULL, NULL),
	(566, 'NG', 'NGA', 234, 'Nigeria', '�frica', NULL, 'NGN', 'Naira nigeriana'),
	(570, 'NU', 'NIU', 683, 'Niue', 'Ocean�a', NULL, NULL, NULL),
	(574, 'NF', 'NFK', 0, 'Isla Norfolk', 'Ocean�a', NULL, NULL, NULL),
	(578, 'NO', 'NOR', 47, 'Noruega', 'Europa', NULL, 'NOK', 'Corona noruega'),
	(580, 'MP', 'MNP', 1670, 'Islas Marianas del Norte', 'Ocean�a', NULL, NULL, NULL),
	(581, 'UM', 'UMI', 0, 'Islas Ultramarinas de Estados Unidos', NULL, NULL, NULL, NULL),
	(583, 'FM', 'FSM', 691, 'Micronesia', 'Ocean�a', NULL, NULL, NULL),
	(584, 'MH', 'MHL', 692, 'Islas Marshall', 'Ocean�a', NULL, NULL, NULL),
	(585, 'PW', 'PLW', 680, 'Palaos', 'Ocean�a', NULL, NULL, NULL),
	(586, 'PK', 'PAK', 92, 'Pakist�n', 'Asia', NULL, 'PKR', 'Rupia pakistan�'),
	(591, 'PA', 'PAN', 507, 'Panam�', 'Am�rica', 'Am�rica Central', 'PAB', 'Balboa paname�a'),
	(598, 'PG', 'PNG', 675, 'Pap�a Nueva Guinea', 'Ocean�a', NULL, 'PGK', 'Kina de Pap�a Nueva Guinea'),
	(600, 'PY', 'PRY', 595, 'Paraguay', 'Am�rica', 'Am�rica del Sur', 'PYG', 'Guaran� paraguayo'),
	(604, 'PE', 'PER', 51, 'Per�', 'Am�rica', 'Am�rica del Sur', 'PEN', 'Nuevo sol peruano'),
	(608, 'PH', 'PHL', 63, 'Filipinas', 'Asia', NULL, 'PHP', 'Peso filipino'),
	(612, 'PN', 'PCN', 870, 'Islas Pitcairn', 'Ocean�a', NULL, NULL, NULL),
	(616, 'PL', 'POL', 48, 'Polonia', 'Europa', NULL, 'PLN', 'zloty polaco'),
	(620, 'PT', 'PRT', 351, 'Portugal', 'Europa', NULL, 'EUR', 'Euro'),
	(624, 'GW', 'GNB', 245, 'Guinea-Bissau', '�frica', NULL, NULL, NULL),
	(626, 'TL', 'TLS', 670, 'Timor Oriental', 'Asia', NULL, NULL, NULL),
	(630, 'PR', 'PRI', 1, 'Puerto Rico', 'Am�rica', 'El Caribe', NULL, NULL),
	(634, 'QA', 'QAT', 974, 'Qatar', 'Asia', NULL, 'QAR', 'Rial qatar�'),
	(638, 'RE', 'REU', 262, 'Reuni�n', '�frica', NULL, NULL, NULL),
	(642, 'RO', 'ROU', 40, 'Rumania', 'Europa', NULL, 'RON', 'Leu rumano'),
	(643, 'RU', 'RUS', 7, 'Rusia', 'Asia', NULL, 'RUB', 'Rublo ruso'),
	(646, 'RW', 'RWA', 250, 'Ruanda', '�frica', NULL, 'RWF', 'Franco ruand�s'),
	(654, 'SH', 'SHN', 290, 'Santa Helena', '�frica', NULL, 'SHP', 'Libra de Santa Helena'),
	(659, 'KN', 'KNA', 1869, 'San Crist�bal y Nieves', 'Am�rica', 'El Caribe', NULL, NULL),
	(660, 'AI', 'AIA', 1264, 'Anguila', 'Am�rica', 'El Caribe', NULL, NULL),
	(662, 'LC', 'LCA', 1758, 'Santa Luc�a', 'Am�rica', 'El Caribe', NULL, NULL),
	(666, 'PM', 'SPM', 508, 'San Pedro y Miquel�n', 'Am�rica', 'Am�rica del Norte', NULL, NULL),
	(670, 'VC', 'VCT', 1784, 'San Vicente y las Granadinas', 'Am�rica', 'El Caribe', NULL, NULL),
	(674, 'SM', 'SMR', 378, 'San Marino', 'Europa', NULL, NULL, NULL),
	(678, 'ST', 'STP', 239, 'Santo Tom� y Pr�ncipe', '�frica', NULL, 'STD', 'Dobra de Santo Tom� y Pr�ncipe'),
	(682, 'SA', 'SAU', 966, 'Arabia Saud�', 'Asia', NULL, 'SAR', 'Riyal saud�'),
	(686, 'SN', 'SEN', 221, 'Senegal', '�frica', NULL, NULL, NULL),
	(688, 'RS', 'SRB', 381, 'Serbia', 'Europa', NULL, NULL, NULL),
	(690, 'SC', 'SYC', 248, 'Seychelles', '�frica', NULL, 'SCR', 'Rupia de Seychelles'),
	(694, 'SL', 'SLE', 232, 'Sierra Leona', '�frica', NULL, 'SLL', 'Leone de Sierra Leona'),
	(702, 'SG', 'SGP', 65, 'Singapur', 'Asia', NULL, 'SGD', 'D�lar de Singapur'),
	(703, 'SK', 'SVK', 421, 'Eslovaquia', 'Europa', NULL, 'SKK', 'Corona eslovaca'),
	(704, 'VN', 'VNM', 84, 'Vietnam', 'Asia', NULL, 'VND', 'Dong vietnamita'),
	(705, 'SI', 'SVN', 386, 'Eslovenia', 'Europa', NULL, NULL, NULL),
	(706, 'SO', 'SOM', 252, 'Somalia', '�frica', NULL, 'SOS', 'Chel�n somal�'),
	(710, 'ZA', 'ZAF', 27, 'Sud�frica', '�frica', NULL, 'ZAR', 'Rand sudafricano'),
	(716, 'ZW', 'ZWE', 263, 'Zimbabue', '�frica', NULL, 'ZWL', 'D�lar zimbabuense'),
	(724, 'ES', 'ESP', 34, 'Espa�a', 'Europa', NULL, 'EUR', 'Euro'),
	(732, 'EH', 'ESH', 0, 'Sahara Occidental', '�frica', NULL, NULL, NULL),
	(736, 'SD', 'SDN', 249, 'Sud�n', '�frica', NULL, 'SDD', 'Dinar sudan�s'),
	(740, 'SR', 'SUR', 597, 'Surinam', 'Am�rica', 'Am�rica del Sur', 'SRD', 'D�lar surinam�s'),
	(744, 'SJ', 'SJM', 0, 'Svalbard y Jan Mayen', 'Europa', NULL, NULL, NULL),
	(748, 'SZ', 'SWZ', 268, 'Suazilandia', '�frica', NULL, 'SZL', 'Lilangeni suazi'),
	(752, 'SE', 'SWE', 46, 'Suecia', 'Europa', NULL, 'SEK', 'Corona sueca'),
	(756, 'CH', 'CHE', 41, 'Suiza', 'Europa', NULL, 'CHF', 'Franco suizo'),
	(760, 'SY', 'SYR', 963, 'Siria', 'Asia', NULL, 'SYP', 'Libra siria'),
	(762, 'TJ', 'TJK', 992, 'Tayikist�n', 'Asia', NULL, 'TJS', 'Somoni tayik (de Tayikist�n)'),
	(764, 'TH', 'THA', 66, 'Tailandia', 'Asia', NULL, 'THB', 'Baht tailand�s'),
	(768, 'TG', 'TGO', 228, 'Togo', '�frica', NULL, NULL, NULL),
	(772, 'TK', 'TKL', 690, 'Tokelau', 'Ocean�a', NULL, NULL, NULL),
	(776, 'TO', 'TON', 676, 'Tonga', 'Ocean�a', NULL, 'TOP', 'Panga tongano'),
	(780, 'TT', 'TTO', 1868, 'Trinidad y Tobago', 'Am�rica', 'El Caribe', 'TTD', 'D�lar de Trinidad y Tobago'),
	(784, 'AE', 'ARE', 971, 'Emiratos �rabes Unidos', 'Asia', NULL, 'AED', 'Dirham de los Emiratos �rabes Unidos'),
	(788, 'TN', 'TUN', 216, 'T�nez', '�frica', NULL, 'TND', 'Dinar tunecino'),
	(792, 'TR', 'TUR', 90, 'Turqu�a', 'Asia', NULL, 'TRY', 'Lira turca'),
	(795, 'TM', 'TKM', 993, 'Turkmenist�n', 'Asia', NULL, 'TMM', 'Manat turcomano'),
	(796, 'TC', 'TCA', 1649, 'Islas Turcas y Caicos', 'Am�rica', 'El Caribe', NULL, NULL),
	(798, 'TV', 'TUV', 688, 'Tuvalu', 'Ocean�a', NULL, NULL, NULL),
	(800, 'UG', 'UGA', 256, 'Uganda', '�frica', NULL, 'UGX', 'Chel�n ugand�s'),
	(804, 'UA', 'UKR', 380, 'Ucrania', 'Europa', NULL, 'UAH', 'Grivna ucraniana'),
	(807, 'MK', 'MKD', 389, 'Macedonia', 'Europa', NULL, 'MKD', 'Denar macedonio'),
	(818, 'EG', 'EGY', 20, 'Egipto', '�frica', NULL, 'EGP', 'Libra egipcia'),
	(826, 'GB', 'GBR', 44, 'Reino Unido', 'Europa', NULL, 'GBP', 'Libra esterlina (libra de Gran Breta�a)'),
	(834, 'TZ', 'TZA', 255, 'Tanzania', '�frica', NULL, 'TZS', 'Chel�n tanzano'),
	(840, 'US', 'USA', 1, 'Estados Unidos', 'Am�rica', 'Am�rica del Norte', 'USD', 'D�lar estadounidense'),
	(850, 'VI', 'VIR', 1340, 'Islas V�rgenes de los Estados Unidos', 'Am�rica', 'El Caribe', NULL, NULL),
	(854, 'BF', 'BFA', 226, 'Burkina Faso', '�frica', NULL, NULL, NULL),
	(858, 'UY', 'URY', 598, 'Uruguay', 'Am�rica', 'Am�rica del Sur', 'UYU', 'Peso uruguayo'),
	(860, 'UZ', 'UZB', 998, 'Uzbekist�n', 'Asia', NULL, 'UZS', 'Som uzbeko'),
	(862, 'VE', 'VEN', 58, 'Venezuela', 'Am�rica', 'Am�rica del Sur', 'VEB', 'Bol�var venezolano'),
	(876, 'WF', 'WLF', 681, 'Wallis y Futuna', 'Ocean�a', NULL, NULL, NULL),
	(882, 'WS', 'WSM', 685, 'Samoa', 'Ocean�a', NULL, 'WST', 'Tala samoana'),
	(887, 'YE', 'YEM', 967, 'Yemen', 'Asia', NULL, 'YER', 'Rial yemen� (de Yemen)'),
	(894, 'ZM', 'ZMB', 260, 'Zambia', '�frica', NULL, 'ZMK', 'Kwacha zambiano');

-- Volcando estructura para tabla constructora.remesa
CREATE TABLE IF NOT EXISTS `remesa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mes` int(11) DEFAULT NULL,
  `ano` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla constructora.remesa: ~0 rows (aproximadamente)
DELETE FROM `remesa`;

-- Volcando estructura para tabla constructora.tareas
CREATE TABLE IF NOT EXISTS `tareas` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `operario_id` int(11) unsigned DEFAULT NULL,
  `cliente_id` int(11) DEFAULT NULL,
  `descripcion` varchar(255) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `poblacion` varchar(255) DEFAULT NULL,
  `cod_postal` varchar(10) DEFAULT NULL,
  `provincia_id` int(11) DEFAULT NULL,
  `estado` enum('P','B','R','C') DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `fecha_realizacion` timestamp NULL DEFAULT NULL,
  `anotaciones_anteriores` varchar(255) DEFAULT NULL,
  `anotaciones_posteriores` varchar(255) DEFAULT NULL,
  `fichero` varchar(255) DEFAULT NULL,
  `foto` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `operario_id` (`operario_id`),
  KEY `cliente_id` (`cliente_id`),
  KEY `provincia_id` (`provincia_id`),
  CONSTRAINT `FK_tareas_clientes` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_tareas_tbl_provincias` FOREIGN KEY (`provincia_id`) REFERENCES `tbl_provincias` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_tareas_users` FOREIGN KEY (`operario_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla constructora.tareas: ~0 rows (aproximadamente)
DELETE FROM `tareas`;

-- Volcando estructura para tabla constructora.tbl_comunidadesautonomas
CREATE TABLE IF NOT EXISTS `tbl_comunidadesautonomas` (
  `id` tinyint(4) NOT NULL DEFAULT 0,
  `nombre` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `nombre` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Afiliados de alta';

-- Volcando datos para la tabla constructora.tbl_comunidadesautonomas: ~19 rows (aproximadamente)
DELETE FROM `tbl_comunidadesautonomas`;
INSERT INTO `tbl_comunidadesautonomas` (`id`, `nombre`) VALUES
	(1, 'Andalucía'),
	(2, 'Aragón'),
	(3, 'Asturias (Principado de)'),
	(4, 'Balears (IIles)'),
	(5, 'Canarias'),
	(6, 'Cantabria'),
	(8, 'Castilla y León'),
	(7, 'Castilla-La Mancha'),
	(9, 'Cataluña'),
	(18, 'Ceuta'),
	(10, 'Comunidad Valenciana'),
	(11, 'Extremadura'),
	(12, 'Galicia'),
	(13, 'Madrid (Comunidad de)'),
	(19, 'Melilla'),
	(14, 'Murcia (Región de)'),
	(15, 'Navarra (Comunidad Foral de)'),
	(16, 'País Vasco'),
	(17, 'Rioja (La)');

-- Volcando estructura para tabla constructora.tbl_provincias
CREATE TABLE IF NOT EXISTS `tbl_provincias` (
  `id` int(11) NOT NULL COMMENT 'Código de la provincia de dos digitos',
  `nombre` varchar(50) NOT NULL COMMENT 'Nombre de la provincia',
  `comunidad_id` tinyint(4) NOT NULL COMMENT 'Código de la comunidad a la que pertenece',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `nombre` (`nombre`),
  KEY `FK_ComunidadAutonomaProv` (`comunidad_id`),
  CONSTRAINT `FK_tbl_provincias_tbl_comunidadesautonomas` FOREIGN KEY (`comunidad_id`) REFERENCES `tbl_comunidadesautonomas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Provincias de españa; 99 para seleccionar a Nacional';

-- Volcando datos para la tabla constructora.tbl_provincias: ~52 rows (aproximadamente)
DELETE FROM `tbl_provincias`;
INSERT INTO `tbl_provincias` (`id`, `nombre`, `comunidad_id`) VALUES
	(1, 'Alava', 16),
	(2, 'Albacete', 7),
	(3, 'Alicante', 10),
	(4, 'Almera', 1),
	(5, 'Avila', 8),
	(6, 'Badajoz', 11),
	(7, 'Balears (Illes)', 4),
	(8, 'Barcelona', 9),
	(9, 'Burgos', 8),
	(10, 'Cáceres', 11),
	(11, 'Cádiz', 1),
	(12, 'Castellón', 10),
	(13, 'Ciudad Real', 7),
	(14, 'Córdoba', 1),
	(15, 'Coruña (A)', 12),
	(16, 'Cuenca', 7),
	(17, 'Girona', 9),
	(18, 'Granada', 1),
	(19, 'Guadalajara', 7),
	(20, 'Guipzcoa', 16),
	(21, 'Huelva', 1),
	(22, 'Huesca', 2),
	(23, 'Jaén', 1),
	(24, 'León', 8),
	(25, 'Lleida', 9),
	(26, 'Rioja (La)', 17),
	(27, 'Lugo', 12),
	(28, 'Madrid', 13),
	(29, 'Málaga', 1),
	(30, 'Murcia', 14),
	(31, 'Navarra', 15),
	(32, 'Ourense', 12),
	(33, 'Asturias', 3),
	(34, 'Palencia', 8),
	(35, 'Palmas (Las)', 5),
	(36, 'Pontevedra', 12),
	(37, 'Salamanca', 8),
	(38, 'Santa Cruz de Tenerife', 5),
	(39, 'Cantabria', 6),
	(40, 'Segovia', 8),
	(41, 'Sevilla', 1),
	(42, 'Soria', 8),
	(43, 'Tarragona', 9),
	(44, 'Teruel', 2),
	(45, 'Toledo', 7),
	(46, 'Valencia', 10),
	(47, 'Valladolid', 8),
	(48, 'Vizcaya', 16),
	(49, 'Zamora', 8),
	(50, 'Zaragoza', 2),
	(51, 'Ceuta', 18),
	(52, 'Melilla', 19);

-- Volcando estructura para tabla constructora.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) unsigned NOT NULL DEFAULT 0,
  `cif` varchar(15) NOT NULL DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `direccion` varchar(50) DEFAULT NULL,
  `rol` enum('A','O') DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla constructora.users: ~1 rows (aproximadamente)
DELETE FROM `users`;
INSERT INTO `users` (`id`, `cif`, `name`, `email`, `email_verified_at`, `telefono`, `direccion`, `rol`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(1, '0', 'Pablo Bejarano', 'pablobejarano2005@gmail.com', NULL, NULL, NULL, NULL, '$2y$12$CgPfe565n2hbiwBL80SeV.44j60mw3QpyYenei/URx2M4pNjxEgm2', NULL, '2025-01-31 08:06:15', '2025-01-31 08:06:15', NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
